[#function getAssetLink node linkProperty]
    [#assign assetlink = ""]
    [#if node.hasProperty(linkProperty)]
        [#assign uuid = node.getProperty(linkProperty).getString()!]
        [#if uuid?has_content && !uuid?starts_with("jcr:")]
            [#assign uuid = "jcr:"+ uuid!]
        [/#if]
        [#assign assetlink = damfn.getAssetLink(uuid, "original")!]
    [/#if]
    [#return assetlink]
[/#function]


[#function getLink urlNode]
    [#assign link = ""]
    [#if urlNode?has_content && urlNode.hasProperty("field")]
        [#assign contentNode = cmsfn.asContentMap(urlNode)!]
        [#assign linkType = contentNode.field!]
        [#-------------- ASSIGNMENTS FOR EACH TYPE --------------]
        [#if linkType=="page"]
            [#assign target = cmsfn.contentById(contentNode.page, "website")!]
            [#--Ensure target node exists and it's not deleted--]
            [#if target?has_content && !cmsfn.asJCRNode(target).hasProperty("mgnl:deleted")]
                [#assign link = cmsfn.link(target)!]
            [/#if]
        [#elseif linkType=="external"]
            [#assign tempLink = (cmsfn.externalLink(contentNode, "external")!)]
            [#if tempLink?has_content]
                [#assign link = tempLink + "\" target=\"_blank"]
            [/#if]
        [/#if]
    [/#if]
    [#return link]
[/#function]

[#function getLink2 urlNode]
    [#assign link = ""]
    [#if urlNode?has_content && urlNode.hasProperty("field")]
        [#assign contentNode = cmsfn.asContentMap(urlNode)!]
        [#assign linkType = contentNode.field!]
        [#-------------- ASSIGNMENTS FOR EACH TYPE --------------]
        [#if linkType=="page"]
            [#assign target = cmsfn.contentByPath(contentNode.page)!]
            [#--Ensure target node exists and it's not deleted--]
            [#if target?has_content && !cmsfn.asJCRNode(target).hasProperty("mgnl:deleted")]
                [#assign link = cmsfn.link(target)!]
            [/#if]
        [#elseif linkType=="external"]
            [#assign tempLink = (cmsfn.externalLink(contentNode, "external")!)]
            [#if tempLink?has_content]
                [#assign link = tempLink + "\" target=\"_blank"]
            [/#if]
        [/#if]
    [/#if]
    [#return link]
[/#function]

[#function getLinkByReference contentMap linkProperty workspace]
    [#assign link = ""]
    [#if contentMap?has_content && cmsfn.asJCRNode(contentMap).hasProperty(linkProperty)]
        [#assign target = cmsfn.contentByPath(cmsfn.asJCRNode(contentMap).getProperty(linkProperty).getString()!, workspace)!]
        [#if target?has_content && !cmsfn.asJCRNode(target).hasProperty("mgnl:deleted")]
            [#assign link = cmsfn.link(target)!]
        [/#if]
    [/#if]
    [#return link]
[/#function]

[#function getPageLink contentMap linkProperty]
    [#return getLinkByReference(contentMap, linkProperty, 'website')]
[/#function]